"""initial_schema

Revision ID: 62c36cb03062
Revises: 
Create Date: 2026-04-27 09:41:04.152460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62c36cb03062'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'name', name='uq_collection_name_per_session')
    )
    op.create_index(op.f('ix_collections_session_id'), 'collections', ['session_id'], unique=False)
    op.create_table('dashboards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'name', name='uq_dashboard_name_per_session')
    )
    op.create_index(op.f('ix_dashboards_session_id'), 'dashboards', ['session_id'], unique=False)
    op.create_table('data_source_connections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_session_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source_type', sa.Enum('POSTGRESQL', 'MYSQL', 'SQLITE', 'JSON', name='datasourcetype'), nullable=False),
    sa.Column('connection_string', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ERROR', 'PENDING', name='connectionstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_source_connections_user_session_id'), 'data_source_connections', ['user_session_id'], unique=False)
    op.create_table('render_mode_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('ui_library', sa.String(), nullable=True),
    sa.Column('design_system_ref', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', name='uq_render_mode_session')
    )
    op.create_index(op.f('ix_render_mode_profiles_session_id'), 'render_mode_profiles', ['session_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('rag_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('vector_store_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('connection_params_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('last_validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', name='uq_vector_store_config_session')
    )
    op.create_index(op.f('ix_vector_store_configs_session_id'), 'vector_store_configs', ['session_id'], unique=False)
    op.create_table('widgets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('extraction_id', sa.String(), nullable=False),
    sa.Column('widget_type', sa.String(), nullable=False),
    sa.Column('selection_source', sa.String(), nullable=False),
    sa.Column('render_mode', sa.String(), nullable=False),
    sa.Column('spec_json', sa.Text(), nullable=False),
    sa.Column('is_saved', sa.Boolean(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('saved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'display_name', name='uq_widget_display_name_per_session')
    )
    op.create_index(op.f('ix_widgets_session_id'), 'widgets', ['session_id'], unique=False)
    op.create_index('ix_widgets_session_saved', 'widgets', ['session_id'], unique=False, postgresql_where='is_saved = TRUE')
    op.create_table('collection_widgets',
    sa.Column('collection_id', sa.String(), nullable=False),
    sa.Column('widget_id', sa.String(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['widget_id'], ['widgets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collection_id', 'widget_id')
    )
    op.create_index('ix_collection_widgets_widget_id', 'collection_widgets', ['widget_id'], unique=False)
    op.create_table('dashboard_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dashboard_id', sa.String(), nullable=False),
    sa.Column('widget_id', sa.String(), nullable=False),
    sa.Column('grid_x', sa.Integer(), nullable=False),
    sa.Column('grid_y', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('z_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['widget_id'], ['widgets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dashboard_id', 'widget_id', name='uq_dashboard_item_widget')
    )
    op.create_index(op.f('ix_dashboard_items_dashboard_id'), 'dashboard_items', ['dashboard_id'], unique=False)
    op.create_table('widget_cache_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('widget_id', sa.String(), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('data_schema_hash', sa.String(length=64), nullable=False),
    sa.Column('connection_id', sa.String(), nullable=True),
    sa.Column('widget_type', sa.String(length=32), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['data_source_connections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['user_sessions.session_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['widget_id'], ['widgets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cache_connection_id', 'widget_cache_entries', ['connection_id'], unique=False)
    op.create_index('ix_cache_session_invalidated', 'widget_cache_entries', ['session_id', 'invalidated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cache_session_invalidated', table_name='widget_cache_entries')
    op.drop_index('ix_cache_connection_id', table_name='widget_cache_entries')
    op.drop_table('widget_cache_entries')
    op.drop_index(op.f('ix_dashboard_items_dashboard_id'), table_name='dashboard_items')
    op.drop_table('dashboard_items')
    op.drop_index('ix_collection_widgets_widget_id', table_name='collection_widgets')
    op.drop_table('collection_widgets')
    op.drop_index('ix_widgets_session_saved', table_name='widgets', postgresql_where='is_saved = TRUE')
    op.drop_index(op.f('ix_widgets_session_id'), table_name='widgets')
    op.drop_table('widgets')
    op.drop_index(op.f('ix_vector_store_configs_session_id'), table_name='vector_store_configs')
    op.drop_table('vector_store_configs')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_render_mode_profiles_session_id'), table_name='render_mode_profiles')
    op.drop_table('render_mode_profiles')
    op.drop_index(op.f('ix_data_source_connections_user_session_id'), table_name='data_source_connections')
    op.drop_table('data_source_connections')
    op.drop_index(op.f('ix_dashboards_session_id'), table_name='dashboards')
    op.drop_table('dashboards')
    op.drop_index(op.f('ix_collections_session_id'), table_name='collections')
    op.drop_table('collections')
    # ### end Alembic commands ###
