/**
 * E2E tests for Feature 003 — Data Agent quickstart scenarios.
 *
 * Prerequisites (handled by global-setup.ts):
 *   - Backend running at http://127.0.0.1:8000 with MOCK_LLM_RESPONSES=true
 *   - SQLite fixture connection seeded for session E2E_SESSION_ID
 *
 * Scenarios covered:
 *   Esc 1  — US1: successful SQL extraction → AgentTrace visible
 *   Esc 2  — US2: AgentTrace collapse / expand
 *   Esc 9  — No active connection → NO_CONNECTION error with /setup reference
 *   Esc 10 — Truncation message visible in trace summary
 *   Esc 11 — Simple message → no AgentTrace rendered
 */

import { test, expect, Page } from "@playwright/test";
import { E2E_SESSION_ID } from "./global-setup";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

async function sendMessage(page: Page, message: string): Promise<void> {
  const input = page.getByRole("textbox", { name: "Mensaje" });
  await input.fill(message);
  await page.getByRole("button", { name: "Enviar" }).click();
}

async function waitForAssistantReply(page: Page) {
  const log = page.getByRole("log");
  const bubble = log.locator('[data-role="assistant"]').last();
  await expect(bubble).toBeVisible({ timeout: 10000 });
  return bubble;
}

// Inject the seeded session ID so the backend finds the active connection.
async function gotoWithSession(page: Page): Promise<void> {
  await page.goto("/");
  // Override the session ID generated by useChat with the seeded one.
  await page.evaluate(
    (sid) => window.localStorage.setItem("e2e_session_override", sid),
    E2E_SESSION_ID
  );
}

// ---------------------------------------------------------------------------
// Escenario 9 — Sin conexión activa (no setup required — fresh session)
// ---------------------------------------------------------------------------

test.describe("Esc 9 — No active connection", () => {
  test("returns NO_CONNECTION error with /setup reference", async ({ page }) => {
    await page.goto("/");

    await sendMessage(page, "muéstrame las ventas por mes");
    const bubble = await waitForAssistantReply(page);

    await expect(bubble).toContainText("/setup");

    const traceBlock = bubble.locator('[data-role="agent-trace"]');
    await expect(traceBlock).toBeVisible();
  });
});

// ---------------------------------------------------------------------------
// Escenario 11 — Compatibilidad hacia atrás (simple intent)
// ---------------------------------------------------------------------------

test.describe("Esc 11 — Simple intent backward compatibility", () => {
  test("simple message has no AgentTrace", async ({ page }) => {
    await page.goto("/");

    await sendMessage(page, "hola");
    const bubble = await waitForAssistantReply(page);

    await expect(bubble.locator('[data-role="agent-trace"]')).toHaveCount(0);
  });
});

// ---------------------------------------------------------------------------
// Escenarios 1 + 2 — SQL extraction + AgentTrace UI
// (require seeded connection → useChat must send E2E_SESSION_ID)
// ---------------------------------------------------------------------------

test.describe("Esc 1+2 — SQL extraction with AgentTrace", () => {
  test.beforeEach(async ({ page }) => {
    // Intercept the chat API call and inject the seeded session ID.
    await page.route("**/api/chat/messages", async (route) => {
      const body = route.request().postDataJSON() as Record<string, string>;
      await route.continue({
        postData: JSON.stringify({ ...body, session_id: E2E_SESSION_ID }),
      });
    });
    await page.goto("/");
  });

  test("Esc 1 — extraction returns rows and AgentTrace is visible", async ({ page }) => {
    await sendMessage(page, "muéstrame las ventas por mes");
    const bubble = await waitForAssistantReply(page);

    // Response text confirms rows found
    await expect(bubble).toContainText("Encontré");

    // AgentTrace block rendered and collapsed by default
    const traceBlock = bubble.locator('[data-role="agent-trace"]');
    await expect(traceBlock).toBeVisible();
    await expect(traceBlock).not.toHaveAttribute("open");

    // Summary contains pipeline label and row count
    const summary = traceBlock.locator("summary");
    await expect(summary).toContainText("Agent Trace");
    await expect(summary).toContainText(/sql/i);
  });

  test("Esc 2 — AgentTrace expands and collapses", async ({ page }) => {
    await sendMessage(page, "muéstrame las ventas por mes");
    const bubble = await waitForAssistantReply(page);

    const traceBlock = bubble.locator('[data-role="agent-trace"]');
    await expect(traceBlock).toBeVisible();

    // Expand
    await traceBlock.locator("summary").click();
    await expect(traceBlock).toHaveAttribute("open");

    // Collapse
    await traceBlock.locator("summary").click();
    await expect(traceBlock).not.toHaveAttribute("open");
  });

  test("Esc 2 — trace persists after a second message", async ({ page }) => {
    await sendMessage(page, "muéstrame las ventas por mes");
    await waitForAssistantReply(page);

    // Send a second message
    await sendMessage(page, "gracias");
    await waitForAssistantReply(page);

    // The first trace must still be in the DOM
    const allTraces = page.locator('[data-role="agent-trace"]');
    await expect(allTraces).toHaveCount(1); // only complex intent produces a trace
  });
});

// ---------------------------------------------------------------------------
// Escenario 10 — Truncation message
// (requires MAX_ROWS_PER_EXTRACTION=4 in backend env for this test)
// Skipped unless PLAYWRIGHT_TEST_TRUNCATION env var is set.
// ---------------------------------------------------------------------------

test.describe("Esc 10 — Truncation", () => {
  test.skip(
    !process.env.PLAYWRIGHT_TEST_TRUNCATION,
    "Set PLAYWRIGHT_TEST_TRUNCATION=1 to run this scenario (requires MAX_ROWS_PER_EXTRACTION=4 in backend)"
  );

  test("truncated result shows truncation message", async ({ page }) => {
    await page.route("**/api/chat/messages", async (route) => {
      const body = route.request().postDataJSON() as Record<string, string>;
      await route.continue({
        postData: JSON.stringify({ ...body, session_id: E2E_SESSION_ID }),
      });
    });
    await page.goto("/");

    await sendMessage(page, "dame todas las filas de sales");
    const bubble = await waitForAssistantReply(page);

    await expect(bubble).toContainText("truncado");
  });
});
